"""
LLM02 — Insecure Output Handling
=================================
Demonstrates what happens when LLM-generated content is rendered or
executed without sanitisation — enabling XSS and command injection.

Vulnerable path : raw HTML/command string returned directly to caller.
Secure path     : HTML sanitised, event-handlers stripped, disclaimer added.
"""

import re
from fastapi import APIRouter
from .shared import Prompt

router = APIRouter(prefix="/llm02", tags=["LLM02 - Insecure Output Handling"])


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _generate_article(topic: str) -> str:
    """
    Simulate an LLM generating content about a topic.
    When the topic contains XSS or injection keywords the model is 'tricked'
    into producing malicious output — the exact risk LLM02 describes.
    """
    t = topic.lower()
    if "xss" in t or "script" in t or "click" in t:
        return (
            f"<p>Article about {topic}:</p>"
            f'<button onclick="alert(\'XSS Vulnerability!\')">Click me for security info</button>'
            f"<p>This demonstrates how an LLM can be manipulated to output JavaScript.</p>"
        )
    if "command" in t or "injection" in t:
        return f"filename_generated_by_llm; echo 'hacked' > /tmp/pwned.txt"
    return f"<p>Article about {topic}:</p><p>This is a safe article generated by the LLM.</p>"


def _sanitize_html(html: str) -> str:
    """Strip script tags, inline event handlers, and dangerous embedded elements."""
    # Remove <script>…</script>
    html = re.sub(r'<script[^>]*>.*?</script>', '', html, flags=re.IGNORECASE | re.DOTALL)
    # Remove on* event attributes  (onclick=, onerror=, …)
    html = re.sub(r'\s*on\w+\s*=\s*["\'][^"\']*["\']', '', html, flags=re.IGNORECASE)
    html = re.sub(r'\s*on\w+\s*=\s*[^\s>]*',           '', html, flags=re.IGNORECASE)
    # Remove iframe, embed, object, script elements entirely
    html = re.sub(r'<(iframe|embed|object|script)[^>]*>.*?</\1>', '', html,
                  flags=re.IGNORECASE | re.DOTALL)
    return html


def _detect_dangerous_patterns(content: str) -> list:
    """Return a list of human-readable warnings for any dangerous patterns found."""
    warnings = []
    if re.search(r'onclick|onerror|onload|script', content, re.IGNORECASE):
        warnings.append("Script/event-handler content detected and sanitised.")
    if re.search(r'[;|&`$()]', content):
        warnings.append("Command injection characters detected.")
    return warnings


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("/vulnerable")
def llm02_vulnerable(prompt: Prompt):
    """
    Vulnerable: raw LLM output returned with no sanitisation.
    If the frontend renders this as HTML, any embedded JavaScript executes.
    """
    article = _generate_article(prompt.text)
    return {
        "mode": "vulnerable",
        "topic": prompt.text,
        "raw_output": article,
        "message": "Output rendered as-is — vulnerable to XSS and command injection.",
    }


@router.post("/secure")
def llm02_secure(prompt: Prompt):
    """
    Secure: three-step pipeline applied to every LLM response.
      1. Sanitise HTML (strip event handlers and dangerous tags).
      2. Validate — report anything suspicious that was removed.
      3. Prepend an AI-generated-content disclaimer.
    """
    raw = _generate_article(prompt.text)
    sanitized = _sanitize_html(raw)
    warnings  = _detect_dangerous_patterns(raw)   # warn on what was in the *raw* output

    disclaimer = (
        "<div style='background:#fff3cd;padding:10px;margin-bottom:10px;border-radius:4px;'>"
        "<strong>⚠️ AI-Generated Content:</strong> This was generated by an AI and may contain inaccuracies."
        "</div>"
    )

    return {
        "mode": "secure",
        "topic": prompt.text,
        "sanitized_output": disclaimer + sanitized,
        "warnings": warnings,
        "message": "Output sanitised and validated before delivery.",
    }
